---
- name: Update apt cache
  apt: update_cache=yes

- name: Make sure apt can use https
  apt: "name={{ item }} state=present"
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Apt Key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present

- name: Add Apt Repository for node
  apt_repository: "repo='deb https://deb.nodesource.com/node_0.12 {{ ansible_distribution_release | lower }} main' state=present"

- name: Add Apt src Repository for node
  apt_repository: "repo='deb-src https://deb.nodesource.com/node_0.12 {{ ansible_distribution_release | lower }} main' state=present"

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install node
  apt: "name={{ item }} state=present"
  with_items:
    - nodejs